development:
  adapter: mysql2
  database: concerning_college_development
  user: root
  password:
  host: localhost
  pool: 5
  timeout: 5000

staging:
  adapter: mysql2
  database: concerning_college_staging
  user: root
  password:
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: rails
  user: rails
  password: XrBIOMGZ20
  host: localhost
  pool: 5
  timeout: 5000

